# Generated by Django 4.2.2 on 2023-06-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("username", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=16)),
                ("email", models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(name="Teacher",),
    ]
