# Generated by Django 4.2.2 on 2023-07-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisments", options={"verbose_name_plural": "Advertisements"},
        ),
        migrations.AlterModelOptions(
            name="article", options={"verbose_name_plural": "Articles"},
        ),
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="comments", options={"verbose_name_plural": "Comments"},
        ),
        migrations.AlterModelOptions(
            name="tag", options={"verbose_name_plural": "Tags"},
        ),
    ]
