# Generated by Django 4.2.2 on 2023-06-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_users_delete_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("image", models.ImageField(upload_to="articles/images")),
                (
                    "author_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.users"
                    ),
                ),
            ],
        ),
    ]
