# Generated by Django 4.2.2 on 2023-06-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_tag_posttag_article_tags"),
    ]

    operations = [
        migrations.DeleteModel(name="PostTag",),
    ]
