# Generated by Django 4.2.2 on 2023-06-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_delete_posttag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(to="home.category"),
        ),
    ]
